#spring.application.name=Student
## Server
#server.port=8080
#
## Database - Update with your MySQL credentials
#spring.datasource.url=jdbc:mysql://localhost:3306/student_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=vikasvighne@123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
## Static resources
#spring.web.resources.static-locations=classpath:/static/
#
## Logging
#logging.level.com.sms=DEBUG

#
# Spring Security
#spring.security.user.name=admin
#spring.security.user.password=admin123
spring.main.allow-circular-references=true
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
#spring.datasource.url=jdbc:mysql://localhost:3306/student_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=vikasvighne@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework=DEBUG